# name of your github action
name: CI
# this will help you specify where to run
on:
  workflow_dispatch:
# this is where the magic happens, each job happens in parallel btw
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Modules and Publish build
        run: |
          sudo apt-get install elfutils -y
          sudo apt install rpm
          npm install
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run publish-linux-app

  macos:
    # Stick with 10.15 due to issue like https://github.com/upscayl/upscayl/issues/98
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Modules and Publish build
        run: |
          npm install
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run publish-mac-app

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Modules and Publish build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run publish-win-app
